name: build-windows-exe

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - 'main.py'
      - 'requirements.txt'
      - '.github/workflows/build-win.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name DirPrefixRenamer main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DirPrefixRenamer
          path: dist/DirPrefixRenamer.exe


